# -*- coding: utf-8 -*-
"""fb_prophet.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15zCuQ4X5RAo6RJmaIW5JEOawLJ1fCD8t
"""

import pandas as pd
from prophet import Prophet

df = pd.read_csv('/content/simple - Sheet1.csv')
df.head()

print(df.dtypes)

df['Net Value'] = df['Net Value'].map(lambda x: float(x))

#df1=df.loc[df['Organization ID'] == 1]
#df11=df1.loc[df['Material Number'] == 500001]
#df12=df11.loc[df['Customer Number'] == 100001]
#df2=df12.loc[df['Region'] == 'TX']

#df2.head()

df2 = df[['Net Value','Billing Date']]
df2.head()

d = df2.groupby('Billing Date').sum()

d.head()

d.to_frame()

df4 = df3.rename(columns={'Billing Date':'ds','Net Value':'y'})
df4.head()

df4.head()

print(df4.dtypes)

df['Year'] = df['BillingDate'].apply(lambda x: str(x)[-4:])
df['Day'] = df['BillingDate'].apply(lambda x: str(x)[3:5])
df['Month'] = df['BillingDate'].apply(lambda x: str(x)[:2])
df['ds'] = pd.DatetimeIndex(df['Year']+'-'+df['Month']+'-'+df['Day'])

df.drop(['BillingDate', 'Year', 'Month', 'Day'], axis=1, inplace=True)

df.head()

df5 = df.rename(columns={'NetValue':'y'})

df5.head()

print(df5.dtypes)

df5['y'] = pd.to_numeric(df5['y'],errors = 'coerce')

prophet = Prophet()
prophet.fit(df5)

future = prophet.make_future_dataframe(periods=100)
future.tail()

forecast = prophet.predict(future)
forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail()

forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].head()

forecast.to_csv("simple_res_final.csv")